project:
  type: book

book:
  title: "Mappeeksamen IDR4000"
  author: "Anders Nybakk"
  date: "2024-09-10"
  chapters:
    - index.qmd
    - 01-Reliabilitet.qmd
    - 02-regression-models.qmd
    - 03-statistical-inference.qmd
    - 04-study-design.qmd
    - 05-repeated-measurements.qmd
    - 06-vitenskapsteori.qmd
    - 07-laboratory-report.qmd
    - references.qmd

bibliography: resources/bib-final.bib

format: pdf



